### ISSUE TITLE
Note of appreciation

### ISSUE THREAD

**Issue by pccasto** [grrr-amsterdam/guidelines#8]
Dank je !

I ran across this repository when searching for work-flows using One Flow using pull requests, rather than direct merges. Google led me to your [guidelines/git/branches/README.md](../blob/master/git/branches/README.md).
Your approach seems to fit very nicely with a flow I will to suggest to a team I am working with.

I then went on to explore your other guidelines. You have done a very nice job of laying out many of the details. Not all of these match with our expected way of work, but it can give us a starting point.

I appreciate you creating this, and releasing this under the MIT license! I think we will be able to make good use of it.

Best regards,
Paul

**Comment by harmenjanssen** [comment]
Thanks, that is so nice to hear. 
I'm happy to have helped, that's what open source development is all about! 

We've been using One Flow for a long time now and it's still our preferred way of working.

Kind regards, good luck!

Harmen

**Comment by pccasto** [comment]
Hi Harmen,

You are welcome. 

I have forked, and started editing the documentation to account for our approach. We are going to use the "variation - develop + master", since we are deploying releases to users, rather than doing CD. It seems like the best approach for us.

Along the way, I noticed that at least three of your URL links were pointed to google searches for the links, rather than the source links themselves, just in case you may want to change those:
```
$ git diff | grep google
-We follow these guidelines as composed by Thoughtbot: [https://github.com/thoughtbot/guides/tree/master/code-review](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fthoughtbot%2Fguides%2Ftree%2Fmaster%2Fcode-review&sa=D&sntz=1&usg=AFQjCNEKhEQHkQFrbsnXflVPlOOPE-xbCA)
-� Pro-tip: grab this git alias to drop into interactive rebase starting at the first commit of your branch: [https://github.com/harmenjanssen/dotfiles/blob/master/git config#L46](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fharmenjanssen%2Fdotfiles%2Fblob%2Fmaster%2Fgitconfig%23L46&sa=D&sntz=1&usg=AFQjCNHIM7wYxfEHyqlfOgI3KMeoIO-4lA)
-- Similarly, when committing changes that should've been part of a previous commit, use `git commit --fixup` and `git rebase -i` to quickly append your changes to any previous commit. See for more info on this technique: [https://robots.thoughtbot.com/autosquashing-git-commits](https://www.google.com/url?q=https%3A%2F%2Frobots.thoughtbot.com%2Fautosquashing-git-commits&sa=D&sntz=1&usg=AFQjCNEw94nfXJ5K92v8eenzZQkFUvMLlQ)
```

Best regards,
Paul

**Comment by harmenjanssen** [comment]
Wow, that is _so_ weird. I wonder how that happened. Thanks, I've fixed those links right away.

> We are going to use the "variation - develop + master", since we are deploying releases to users, rather than doing CD. It seems like the best approach for us.

Just know that tags can _probably_ solve the same problems a separate branch is doing for you.  
But in the end, you just have to be comfortable with your workflow and switching from one model to the other is relatively painless. 🙂

**Comment by pccasto** [comment]
I know that. and you know that :-), but yes, this is about team comfort level, and expectation of the novice GitHub user when they go to pull the "latest" source.  But thanks for mentioning that, just in case I wasn't aware :-)

The project has been successfully going on for several years, outside of shared source control.  About a year ago, the latest release started to be added to GitHub as an atomic check-in to master.  That was a huge step forward. I only started participating with this team a few months ago. I am assisting them in taking some additional steps forward - providing them with some options, and advice, but not trying to changes things too dramatically, or based solely on how I might approach things.  Another place where "that's what open source is all about." :-)

**Comment by pccasto** [comment]
While I'm at it, I just found that on the web-site:
https://guidelines.grrr.tech/coding-standards/js/
the link back to the general coding standards doesn't work.

**Comment by harmenjanssen** [comment]
> The project has been successfully going on for several years, outside of shared source control. About a year ago, the latest release started to be added to GitHub as an atomic check-in to master. That was a huge step forward. I only started participating with this team a few months ago. I am assisting them in taking some additional steps forward - providing them with some options, and advice, but not trying to changes things too dramatically, or based solely on how I might approach things. Another place where "that's what open source is all about." :-)

Sounds like  a good job. 🙂 

> While I'm at it, I just found that on the web-site:
https://guidelines.grrr.tech/coding-standards/js/
the link back to the general coding standards doesn't work.

Gee, it's a good thing you came by to fork this. 😅 
Fixed the link, thanks!

**Comment by pccasto** [comment]
Not so much a job, more of a way to avoid doing some of the things I really should be doing around the house...
Again, Thanks, and you are welcome.
